server:
  port: '8082'

spring:
  profiles:
    active: qa
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '20000'
    url: jdbc:postgresql://localhost:5432/dcbapp
    password: eden258
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer !!

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '20000'
    url: jdbc:postgresql://localhost:5432/dcbapp-qa
    password: eden258
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer !!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '5'
      connection-timeout: '20000'
    url: jdbc:postgresql://localhost:5432/dcbapp-prod
    password: eden258
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to Daily Code Buffer !!
